=== JavierCastroMagro03/rpg-database-simulation/Archivos_Práctica II/Doc/Objetos.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="objetos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="armas">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="arma" maxOccurs="20" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Nombre">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="25" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:integer" name="Damage" />
                    <xs:element type="xs:string" name="Tipo" />
                    <xs:element type="xs:string" name="Habilidad" />
                    <xs:element name="Rareza">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Common" />
                          <xs:enumeration value="Uncommon" />
                          <xs:enumeration value="Rare" />
                          <xs:enumeration value="Very Rare" />
                          <xs:enumeration value="Legendary" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:integer" name="Valor" />
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="armaduras">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="armadura" maxOccurs="20" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Nombre">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="25" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:integer" name="Defensa" />
                    <xs:element type="xs:string" name="Pasiva" />
                    <xs:element type="xs:string" name="Tipo" />
                    <xs:element name="Rareza">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Common" />
                          <xs:enumeration value="Uncommon" />
                          <xs:enumeration value="Rare" />
                          <xs:enumeration value="Very Rare" />
                          <xs:enumeration value="Legendary" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:integer" name="Valor" />
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="consumibles">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="consumible" maxOccurs="20" minOccurs="1">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="Nombre">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:maxLength value="25" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:string" name="Tipo" />
                    <xs:element type="xs:string" name="Efecto" />
                    <xs:element name="Rareza">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="Common" />
                          <xs:enumeration value="Uncommon" />
                          <xs:enumeration value="Rare" />
                          <xs:enumeration value="Very Rare" />
                          <xs:enumeration value="Legendary" />
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>
                    <xs:element type="xs:integer" name="Valor" />
                  </xs:sequence>
                  <xs:attribute type="xs:byte" name="id" use="required" />
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== JavierCastroMagro03/rpg-database-simulation/Archivos_Práctica II/Doc/Objetos - fallos.xml
<objetos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Objetos.xsd">
      <armas>
      </armas>

      <armaduras>
            <armadura id="21">
                  <Nombre>Simple Robefsjadfskaufdsahgsfdkuafdasd</Nombre>
                  <Defensa>10</Defensa>
                  <Pasiva></Pasiva>
                  <Tipo>Chestplate</Tipo>
                  <Rareza>Common</Rareza>
                  <Valor>20</Valor>
            </armadura>

            <armadura id="22">
                  <Nombre>Robe of Summer</Nombre>
                  <Defensa>10</Defensa>
                  <Pasiva>Temperature Adjustment</Pasiva>
                  <Tipo>Chestplate</Tipo>
                  <Rareza>Uncommon</Rareza>
                  <Valor>250</Valor>
            </armadura>
      </armaduras>

      <consumibles>
            <consumible id="41">
                  <Nombre>Potion of Healing</Nombre>
                  <Tipo>Potions</Tipo>
                  <Efecto>Healing</Efecto>
                  <Rareza>Comon</Rareza>
                  <Valor>60</Valor>
            </consumible>

            <consumible id="42">
                  <Nombre>Potion of Speed</Nombre>
                  <Tipo>Potions</Tipo>
                  <Efecto>Boost</Efecto>
                  <Rareza>Uncommon</Rareza>
                  <Valor>45</Valor>
            </consumible>
      </consumibles>
</objetos>

=== JavierCastroMagro03/rpg-database-simulation/Archivos_Práctica II/Doc/Objetos.xml
<?xml version="1.0" encoding="UTF-8"?>
<objetos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Objetos.xsd">
      <armas>
            <arma id="1">
                  <Nombre>Staff of the Emperor</Nombre>
                  <Damage>10</Damage>
                  <Tipo>Staff</Tipo>
                  <Habilidad>Piercing Strike</Habilidad>
                  <Rareza>Rare</Rareza>
                  <Valor>190</Valor>
            </arma>

            <arma id="2">
                  <Nombre>Spiderstep Staff</Nombre>
                  <Damage>8</Damage>
                  <Tipo>Staff</Tipo>
                  <Habilidad>Rush Attack</Habilidad>
                  <Rareza>Uncommon</Rareza>
                  <Valor>180</Valor>
            </arma>
      </armas>

      <armaduras>
            <armadura id="21">
                  <Nombre>Simple Robe</Nombre>
                  <Defensa>10</Defensa>
                  <Pasiva></Pasiva>
                  <Tipo>Chestplate</Tipo>
                  <Rareza>Common</Rareza>
                  <Valor>20</Valor>
            </armadura>

            <armadura id="22">
                  <Nombre>Robe of Summer</Nombre>
                  <Defensa>10</Defensa>
                  <Pasiva>Temperature Adjustment</Pasiva>
                  <Tipo>Chestplate</Tipo>
                  <Rareza>Uncommon</Rareza>
                  <Valor>250</Valor>
            </armadura>
      </armaduras>

      <consumibles>
            <consumible id="41">
                  <Nombre>Potion of Healing</Nombre>
                  <Tipo>Potions</Tipo>
                  <Efecto>Healing</Efecto>
                  <Rareza>Common</Rareza>
                  <Valor>60</Valor>
            </consumible>

            <consumible id="42">
                  <Nombre>Potion of Speed</Nombre>
                  <Tipo>Potions</Tipo>
                  <Efecto>Boost</Efecto>
                  <Rareza>Uncommon</Rareza>
                  <Valor>45</Valor>
            </consumible>
      </consumibles>
</objetos>
